server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=MySuperSecretKeyMySuperSecretKey1234567890
app.jwt.expiration-ms=86400000
app.seed.admin-email=admin@ecommerce.com
app.seed.admin-password=Admin@123